// Child Labor Project — mock data store (replace with backend per STRUCTURE.md)
import type {
  User,
  Project,
  Beneficiary,
  ProgressReport,
  LeavingRecord,
} from "./types";

export const users: User[] = [
  {
    id: "u-admin",
    fullName: "System Administrator",
    email: "admin@clp.org",
    role: "admin",
    active: true,
    createdAt: "2024-01-10",
  },
  {
    id: "u-editor",
    fullName: "Mariam Adel",
    email: "editor@clp.org",
    role: "editor",
    active: true,
    createdAt: "2024-02-01",
  },
  {
    id: "u-viewer",
    fullName: "John Director",
    email: "viewer@clp.org",
    role: "viewer",
    active: true,
    createdAt: "2024-02-05",
  },
];

// The system runs a SINGLE project: Child Labor Project.
export const PROJECT_ID = "p-1";

export const projects: Project[] = [
  {
    id: PROJECT_ID,
    projectName: "Child Labor Project",
    countryName: "Egypt",
    responsibleProjectManager: "Karim Mostafa",
    responsibleSponsorshipOfficerIO: "Sara Ibrahim",
    responsibleCountryDirector: "David Okoro",
    createdAt: "2024-01-15",
  },
];

export const beneficiaries: Beneficiary[] = [
  {
    id: "b-1",
    projectId: "p-1",
    beneficiaryNumber: "CLP-0001",
    status: "sponsored",
    firstName: "Mina",
    lastName: "Adel",
    dateOfBirth: "2014-06-12",
    gender: "male",
    photoUrl: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&h=400&fit=crop",
    language: "Arabic",
    village: "Manshiet Nasser",
    healthSituation: "good",
    hobbies: ["Football", "Drawing"],
    favoriteColor: "Blue",
    character: ["Active", "Kind"],
    parentsAlive: "both",
    liveWithBothParents: true,
    liveWith: "both",
    hasSiblings: true,
    siblingsCount: 3,
    typeOfHouse: "mud_brick",
    schoolLevel: "Grade 5",
    schoolPerformance: "good",
    favoriteSubject: "Mathematics",
    futurePlans: "Wants to become an engineer.",
    createdAt: "2024-02-10",
  },
  {
    id: "b-2",
    projectId: "p-1",
    beneficiaryNumber: "CLP-0002",
    status: "entry",
    firstName: "Kyrillos",
    lastName: "Ashraf",
    dateOfBirth: "2016-09-03",
    gender: "female",
    photoUrl: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=400&h=400&fit=crop",
    language: "Arabic",
    village: "Ezbet El Nakhl",
    healthSituation: "average",
    hobbies: ["Reading", "Singing"],
    favoriteColor: "Pink",
    character: ["Shy", "Curious"],
    parentsAlive: "father",
    liveWithBothParents: false,
    liveWith: "father",
    hasSiblings: true,
    siblingsCount: 2,
    typeOfHouse: "reinforced_concrete",
    schoolLevel: "Grade 3",
    schoolPerformance: "average",
    favoriteSubject: "Art",
    futurePlans: "Wants to become a teacher.",
    createdAt: "2024-04-01",
  },
  {
    id: "b-3",
    projectId: "p-1",
    beneficiaryNumber: "CLP-0003",
    status: "priority",
    firstName: "Amgad",
    lastName: "Ramzy",
    dateOfBirth: "2013-01-22",
    gender: "male",
    photoUrl: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=400&h=400&fit=crop",
    language: "Arabic",
    village: "Manshiet Nasser",
    healthSituation: "poor",
    hobbies: ["Cycling", "Swimming"],
    favoriteColor: "Green",
    character: ["Quiet", "Hardworking"],
    parentsAlive: "mother",
    liveWithBothParents: false,
    liveWith: "mother",
    hasSiblings: false,
    typeOfHouse: "mud_brick",
    schoolLevel: "Grade 6",
    schoolPerformance: "weak",
    favoriteSubject: "Science",
    futurePlans: "Wants to become a doctor.",
    createdAt: "2024-03-12",
  },
  {
    id: "b-4",
    projectId: "p-1",
    beneficiaryNumber: "CLP-0004",
    status: "sponsored",
    firstName: "Mahab",
    lastName: "Kamel",
    dateOfBirth: "2015-11-30",
    gender: "female",
    photoUrl: "https://images.unsplash.com/photo-1542103749-8ef59b94f47e?w=400&h=400&fit=crop",
    language: "Arabic",
    village: "Ezbet El Nakhl",
    healthSituation: "good",
    hobbies: ["Dancing", "Reading"],
    favoriteColor: "Yellow",
    character: ["Cheerful", "Confident"],
    parentsAlive: "both",
    liveWithBothParents: true,
    liveWith: "both",
    hasSiblings: true,
    siblingsCount: 4,
    typeOfHouse: "mud_brick",
    schoolLevel: "Grade 4",
    schoolPerformance: "excellent",
    favoriteSubject: "English",
    futurePlans: "Wants to become a pilot.",
    createdAt: "2024-04-15",
  },
];

export const progressReports: ProgressReport[] = [
  {
    id: "r-1",
    beneficiaryId: "b-1",
    reportType: "quarterly",
    period: "Q1",
    cycleYear: 1,
    date: "2024-04-05",
    messageToSponsor:
      "Dear sponsor, thank you for your support. Mina has settled into the program and is attending school regularly.",
    beneficiaryUpdate:
      "Mina enrolled back into Grade 5 and stopped working at the workshop. Attendance is 92% this quarter.",
    authorUserId: "u-editor",
  },
  {
    id: "r-2",
    beneficiaryId: "b-1",
    reportType: "semi_annual",
    period: "H1",
    cycleYear: 1,
    date: "2024-07-10",
    updatePhotoUrl:
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&h=400&fit=crop",
    messageToSponsor:
      "Mina sends his warm greetings and a drawing he made in art class. He is very grateful for your support.",
    beneficiaryUpdate:
      "Health check completed — result: good. Grades improved from average to good. Joined the school football team.",
    authorUserId: "u-editor",
  },
  {
    id: "r-3",
    beneficiaryId: "b-1",
    reportType: "annual",
    period: "Full Year",
    cycleYear: 1,
    date: "2024-12-20",
    messageToSponsor:
      "Year one is complete. Thank you for standing by Mina throughout this year.",
    beneficiaryUpdate:
      "Mina passed Grade 5 and has not returned to labor. The family received a monthly education grant and psychosocial follow-up.",
    authorUserId: "u-editor",
  },
  {
    id: "r-4",
    beneficiaryId: "b-4",
    reportType: "quarterly",
    period: "Q4",
    cycleYear: 1,
    date: "2024-12-05",
    messageToSponsor:
      "Mahab is grateful for the school supplies and sends her warm greetings to her sponsor.",
    beneficiaryUpdate:
      "Mahab scored top marks in English and enjoys the reading club after school.",
    authorUserId: "u-editor",
  },
];

export const leavingRecords: LeavingRecord[] = [];
